image: nexus.asta.ir:4000/maven:3.3.9-jdk-8
variables:
  CATALINA_HOME: "/builds/CATALINA_HOME"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -DinstallDirectory=/node"
  SONAR_OPTS: "-Dsonar.branch=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME"


stages:
    - build
    - test
    - release
    - deploy


build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  except:
    - tags


sonar:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test sonar:sonar $SONAR_OPTS -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
  except:
    - tags


release:
  stage: release
  script:
    - PROJECT_URL="git@git.asta.ir:$GIT_ACCESS_USER/$CI_PROJECT_PATH.git"
    - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
    - |
       if [[ $VERSION == *"SNAPSHOT"* ]]; then
          echo "SNAPSHOT"
       else
          echo "tag creation"
          git tag $VERSION
          git push $PROJECT_URL $VERSION
       fi
  only:
    - master
    - /^releases-.+/
    - /^release-.+/


deploy:
  stage: deploy
  script:
    - mvn -Dmaven.test.skip=true $MAVEN_CLI_OPTS deploy
  only:
    - master
    - /^releases-.+/
    - /^release-.+/